services:
  cmake-build:
    image: cmake-build
    container_name: cmake-build
    build:
      context: .
      dockerfile: cmake-build/Dockerfile
    volumes:
      - ./common:/app/common
      - ./server:/app/server
      - ./client:/app/client

  common:
    image: common
    container_name: common
    build:
      context: .
      dockerfile: common/Dockerfile
    depends_on:
      - cmake-build
    volumes:
      - ./common:/app/common

  server:
    image: server
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - cmake-build
    volumes:
      - ./server:/app/server
      - ./common:/app/common

  client:
    image: client
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - cmake-build
    volumes:
      - ./client:/app/client
      - ./common:/app/common