services:
  cmake-build:
    image: cmake-build
    container_name: cmake-build
    build:
      context: .
      dockerfile: cmake-build/Dockerfile
    volumes:
      - ./common:/app/common
      - ./server:/app/server
#      - ./client:/app/client

  server:
    image: server
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      - cmake-build
    volumes:
      - ./server:/app/server
      - ./common:/app/common

#  client:
#    image: client
#    container_name: client
#    build:
#      context: .
#      dockerfile: client/Dockerfile
#    depends_on:
#      - cmake-build
#      - server
#    volumes:
#      - ./client:/app/client
#      - ./common:/app/common